"""Branded previews and genuinely interactive free samples; never a paywall."""
import json
import re


def academy_header(header):
    """Native mobile disclosure avoids the late JS-expanded-to-collapsed shift."""
    match = re.search(r'<ul id="primary-links" class="nav-links">.*?</ul>', header, re.S)
    if not match:
        raise ValueError('Academy navigation source changed; inspect before building')
    mobile = match.group().replace('class="nav-links"', 'class="academy-mobile-links"')
    header = header.replace(match.group(), match.group().replace('id="primary-links"', 'id="academy-desktop-links"').replace('class="nav-links"', 'class="nav-links academy-desktop-links"'))
    menu = '<details class="academy-native-menu"><summary aria-controls="primary-links">Menu<span class="visually-hidden">: primary navigation</span></summary>' + mobile + '</details>'
    header, count = re.subn(r'<button class="nav-toggle".*?</button>', lambda _: menu, header, count=1, flags=re.S)
    if count != 1:
        raise ValueError('Academy navigation toggle missing')
    return header

def photo(name, alt, *, hero=False):
    return f'<img src="assets/images/academy/{name}-1280.webp" srcset="assets/images/academy/{name}-640.webp 640w, assets/images/academy/{name}-1280.webp 1280w" sizes="(max-width: 44rem) 100vw, 50vw" width="1280" height="853" alt="{alt}" decoding="async" {"fetchpriority=high" if hero else "loading=lazy"}>'


def masthead(other_href, other_label):
    return f'<div class="academy-masthead"><a class="academy-wordmark" href="learning.html"><img src="assets/brand/mark-dark.svg" width="30" height="30" alt="">MATRIX / ACADEMY</a><a class="academy-edition" href="{other_href}">{other_label} ↗</a></div>'


def track_card(partner=False):
    name, label, title, description, href, link = (
        ("partner-practice", "02 / Independent business", "Partner Practice", "Real skills. Thoughtful conversations. Your own direction.", "partners.html", "Explore partner learning")
        if partner else
        ("everyday-matrix", "01 / Everyday life", "Everyday Matrix", "Food, movement, rest. Make room for what matters.", "#sample", "Try a free lesson")
    )
    return f'<a class="academy-choice {"academy-choice--partner" if partner else ""}" href="{href}"><div class="academy-choice__visual">{photo(name, "", hero=not partner)}<span class="academy-cover-index" aria-hidden="true">{"02" if partner else "01"}</span></div><div class="academy-choice__copy"><span class="academy-label">{label}</span><h2>{title}</h2><p>{description}</p><span class="academy-choice__link">{link} <b aria-hidden="true">↗</b></span></div></a>'


def sample_player(practice_copy, partner=False):
    kind = "partner" if partner else "everyday"
    if partner:
        title, subtitle = "An invitation, not a pitch.", "Practise a useful first conversation before sending anything."
        intro = '<div class="academy-principle"><span>01</span><h3>Ask permission.<br>Leave room for no.</h3><p>A good invitation makes the topic and commercial relationship clear. It does not assume someone wants a product or a business conversation.</p></div><div class="academy-formula"><div><b>Context</b><span>What are we talking about?</span></div><span aria-hidden="true">+</span><div><b>Choice</b><span>Would this be useful?</span></div><span aria-hidden="true">+</span><div><b>Clarity</b><span>What is my relationship?</span></div></div>'
        practice = '<h3>Shape a transparent invitation.</h3><p>This is a writing exercise, not an outreach tool. Only contact someone with appropriate permission; nothing is sent from this page.</p><div class="academy-fields"><label for="practice-topic">Choose the conversation<select id="practice-topic" data-choice="topic"><option value="products">Understanding the products</option><option value="business">Understanding independent partner work</option><option value="event">A small product-learning event</option></select></label><label for="practice-format">Choose the format<select id="practice-format" data-choice="format"><option value="guide">A short guide</option><option value="chat">A short conversation</option><option value="questions">A few questions by email</option></select></label></div><div class="academy-plan"><span class="academy-label">Your practice draft</span><p data-plan aria-live="polite"></p></div><p class="academy-small">Adapt this to the actual relationship and local rules. Keep private contacts, financial details and customer information off this site.</p>'
        question = "They say “not interested.” What next?"
        answers = [("pause", "Respect their decision and stop the outreach."), ("pressure", "Follow up repeatedly until they respond."), ("promise", "Promise that the business will work for them.")]
        correct = "Respect their decision. A useful conversation depends on real choice, not persistence after a refusal."
        wrong = "Try again. Permission can be withdrawn; respect a refusal without pressure or promises."
    else:
        title, subtitle = "Make small your starting point.", "One idea. One practice. Something useful to take into tomorrow."
        intro = '<div class="academy-principle"><span>01</span><h3>A smaller plan.<br>A clearer next step.</h3><p>Choose something your day already contains. Attach one small, realistic action to it. Give yourself a simpler option for a difficult day.</p></div><div class="academy-formula"><div><b>A cue</b><span>After something familiar</span></div><span aria-hidden="true">+</span><div><b>An action</b><span>One manageable step</span></div><span aria-hidden="true">+</span><div><b>A fallback</b><span>A smaller version</span></div></div>'
        practice = '<h3>Build a plan for a real day.</h3><p>Choose a starting point. There is no perfect combination and no product to buy.</p><div class="academy-fields"><label for="practice-cue">After I…<select id="practice-cue" data-choice="cue"><option value="breakfast">Finish breakfast</option><option value="home">Arrive home</option><option value="evening">Begin my evening routine</option></select></label><label for="practice-action">I will…<select id="practice-action" data-choice="action"><option value="plan">Write down one priority for tomorrow</option><option value="pause">Pause for a quiet minute</option><option value="prepare">Set out one item for tomorrow</option></select></label></div><div class="academy-plan"><span class="academy-label">Your small-step plan</span><p data-plan aria-live="polite"></p></div><p class="academy-small">This is a general planning exercise, not an individualized exercise, diet or supplement plan. Keep any personal notes privately.</p>'
        question = "You miss three days. What comes next?"
        answers = [("double", "Double the workload to make up for it."), ("smaller", "Resume with a smaller, realistic action."), ("quit", "Abandon the plan because it was not perfect.")]
        correct = "Exactly. Resume with a manageable action and adjust what did not fit. Missing a day is information, not a verdict."
        wrong = "Try again. The aim is a plan you can return to, not punishment or an all-or-nothing rule."
    options = "".join(f'<label class="academy-answer"><input type="radio" name="{kind}-answer" value="{value}"><span>{text}</span></label>' for value, text in answers)
    payload = json.dumps(practice_copy, ensure_ascii=True).replace("<", "\\u003c").replace(">", "\\u003e").replace("&", "\\u0026")
    return f'''<section class="academy-section" id="sample"><div class="container"><div class="academy-section-header"><div><p class="academy-label">{"Partner Practice" if partner else "Everyday Matrix"} / Interactive free sample</p><h2>{title}</h2></div><p>{subtitle}</p></div>
      <div class="academy-player" data-academy="{kind}">
        <script type="application/json" data-practice-copy>{payload}</script>
        <aside class="academy-player__rail"><span class="academy-label">THE PRACTICE ROOM</span><h3>Learn by doing.</h3><ol class="academy-stages"><li><span>01</span>Understand</li><li><span>02</span>Practise</li><li><span>03</span>Check</li></ol><div class="academy-progress-group" hidden data-enhanced><label for="{kind}-progress" data-progress-label>Step 1 of 3</label><progress id="{kind}-progress" value="1" max="3" data-progress>1 of 3</progress></div><p class="academy-small">Just this visit. Your choices are not saved or sent.</p></aside>
        <div class="academy-player__body"><section class="academy-panel" data-panel="0" aria-label="Understand">{intro}</section>
        <section class="academy-panel" data-panel="1" aria-label="Practise">{practice}<noscript><p>Write your own version on paper: choose a familiar cue, or a conversation topic; make the next step clear and leave room to change your mind.</p></noscript></section>
        <section class="academy-panel" data-panel="2" aria-label="Check"><span class="academy-label">A quick reflection</span><h3>{question}</h3><fieldset class="academy-quiz" data-quiz><legend class="visually-hidden">{question}</legend>{options}</fieldset><button class="academy-button academy-button--dark" type="button" data-check hidden>Check my answer <span aria-hidden="true">↗</span></button><p class="academy-feedback" role="status" data-feedback data-correct="{correct}" data-wrong="{wrong}"></p><div class="academy-complete" data-complete hidden><span aria-hidden="true">✓</span><h4>One useful practice, complete.</h4><p>Take the idea with you. This sample is not a qualification or completion of the full course.</p><button class="academy-button academy-button--outline" type="button" data-restart>Try it again ↺</button></div><noscript><details><summary>Read the answer</summary><p>{correct}</p></details></noscript></section>
        <div class="academy-player__controls" hidden data-enhanced><button class="academy-button academy-button--outline" type="button" data-back disabled>← Back</button><span data-step aria-live="polite">01 / 03</span><button class="academy-button academy-button--dark" type="button" data-next>Practise →</button></div></div>
      </div></div></section>'''


def curriculum(course, api, *, partner=False):
    esc = api.esc
    cards = []
    for item in course["modules"]:
        guide = f'<a href="library/{esc(item["guide"], attribute=True)}.html">Related free Library guide ↗</a>' if "guide" in item else ""
        cards.append(f'<details class="academy-module"><summary><span class="academy-module__number">{item["number"]:02d}</span><span class="academy-module__title">{esc(item["title"])}</span><span class="academy-module__expand" aria-hidden="true">+</span></summary><div class="academy-module__inside"><p>{esc(item["outcome"])}</p>{guide}<p class="academy-small">Planned course module · Full lesson not open for enrollment.</p></div></details>')
    phases = [("01—03", "Know the work", "Business basics, costs & product literacy"), ("04—07", "Find your voice", "Marketing, networking, events & speaking"), ("08—10", "Build a practice", "Meetings, team support & measured decisions")] if partner else [("01—03", "Find your rhythm", "Everyday routines, food & movement"), ("04—06", "Understand your choices", "Rest, supplements & testing context"), ("07—08", "Make it your own", "A flexible week & a thoughtful next month")]
    roadmap = "".join(f'<div><span class="academy-label">{number}</span><h3>{title}</h3><p>{text}</p></div>' for number, title, text in phases)
    return f'<section class="academy-section academy-section--white" id="curriculum"><div class="container"><div class="academy-section-header"><div><p class="academy-label">THE COURSE MAP / {len(course["modules"]):02d} PLANNED MODULES</p><h2>{"Skills worth practising." if partner else "Built around real life."}</h2></div><p>{"A practical path through independent partner work. No earnings or lifestyle promises." if partner else "For adults 18+ through older adulthood. Adapt the learning to your circumstances; no supplement or test purchase required."}</p></div><div class="academy-roadmap">{roadmap}</div><div class="academy-curriculum">{"".join(cards)}</div></div></section>'


def closing(partner=False):
    return f'''<section class="academy-section academy-section--dark"><div class="container academy-closing"><div><p class="academy-label">TAKE YOUR NEXT STEP</p><h2>{"Curious is enough." if partner else "A little more clarity.<br>A little more everyday."}</h2><p>{"Explore the work before making a decision. Questions are welcome, and no is always an option." if partner else "Start with the free lesson. Explore the Library. Return when you are ready for another small step."}</p><a class="academy-button" href="{"about.html" if partner else "#sample"}">{"Ask about the learning plan" if partner else "Try the free lesson"} <span aria-hidden="true">↗</span></a><a class="academy-text-link" href="{"learning.html" if partner else "library.html"}">{"Explore everyday learning" if partner else "Browse the free Library"} →</a></div><aside class="academy-status"><span class="academy-label">COURSE STATUS / IN DEVELOPMENT</span><h3>Try the sample.<br>No enrollment required.</h3><p>Not available for purchase. Full courses, pricing and enrollment terms will be reviewed before sales open. There is no payment form or automatic signup here.</p><p class="academy-small">Original independent education. Not an official Zinzino course. Course images are AI-generated illustrations, not actual students, instructors or events.</p></aside></div></section>'''


def experience_summary(partner=False):
    """Public-safe summaries only. No private lesson, media, answer key or draft price."""
    title = "A practice, not a promise." if partner else "Make something useful."
    fit = "For adults exploring independent network marketing with explicit Zinzino context, including people who decide not to join or continue. Not a job offer, earnings forecast or official company qualification." if partner else "For adults 18+ who want a practical everyday system across different schedules and abilities. Not personal medical advice, a treatment plan or a required supplement stack."
    tools = "Cost and decision lab; permission-based conversation practice; communication and event planning." if partner else "Everyday-system planner; supplement and evidence comparison; questions-before-decisions checklist."
    artifact = "A bounded educational project, cost record and reasoned continue, revise, pause or decline memo." if partner else "An ordinary-day plan with fallbacks, optional supplement/testing questions and a practical review point."
    return f'''<section class="academy-section academy-section--brief" id="course-experience"><div class="container academy-experience"><div><p class="academy-label">OPTIONAL DEEPER LEARNING</p><h2>{title}</h2><p>{fit}</p><a class="academy-text-link" href="explore.html">Keep exploring products →</a></div><div class="academy-experience__steps"><article><span>01 / UNDERSTAND</span><h3>Teaching with context.</h3><p>The private course candidate includes written lessons, captioned core videos, worked examples and source notes. Content and learner review remain pending.</p></article><article><span>02 / PRACTISE</span><h3>Three connected labs.</h3><p>{tools} The interactive sample below is free; full course labs are not publicly available.</p></article><article><span>03 / MAKE</span><h3>A capstone you can explain.</h3><p>{artifact} Practice is not a professional credential or evidence of health or business results.</p></article></div></div></section>'''


def access_faq():
    return '''<section class="academy-section academy-section--white" id="access-questions"><div class="container academy-faq"><div><p class="academy-label">CLEAR BEFORE YOU COMMIT</p><h2>Your questions,<br>without the pressure.</h2></div><div><details><summary>What can I use today?</summary><p>The free interactive sample on this page and the main website’s free education. Full courses are in private review and are not open for enrollment.</p></details><details><summary>Will I need to buy products or become a partner?</summary><p>No. The learning paths are optional. Product purchases, course enrollment and business participation are separate decisions. A reasoned decision not to buy or join belongs in the learning.</p></details><details><summary>How will access, progress and support work?</summary><p>Managed accounts, protected lessons and saved progress are being evaluated; they are not active here. Access duration, support capacity, pricing and refund terms will be clearly reviewed before a course can be purchased. This page creates no student account.</p></details><details><summary>Does a source link mean the course is endorsed?</summary><p>No. Sources support specific teaching points. General health guidance is not personal advice, and ingredient research does not automatically establish a finished-product result. This is independent education, not an official Zinzino course.</p></details><details><summary>Can I stay with the free website?</summary><p>Absolutely. Continue through <a href="testing.html">testing journeys</a>, the <a href="library.html">Library</a>, <a href="evidence.html">Evidence</a> and <a href="explore.html">products</a>. You do not need a course to use them.</p></details></div></div></section>'''


def render(data, wellness, partner, api):
    hero = f'<section class="academy-hero"><div class="container">{masthead("#curriculum", "See the course map")}<div class="academy-intro"><h1>Learn it.<br><em>Live it.</em></h1><div class="academy-intro__copy"><p>Ideas are only the beginning. Turn what you learn into something you can actually practise.</p><p>Two paths. One thoughtful next step.</p></div></div><div class="academy-choices">{track_card()}{track_card(True)}</div><p class="academy-preview-note">Course previews · Not available for purchase. Original illustrative imagery.</p></div></section>'
    body = experience_summary() + sample_player(wellness["practice"]) + curriculum(wellness, api)
    body += '<section class="academy-section"><div class="container academy-approach"><div><p class="academy-label">LESS INFORMATION OVERLOAD</p><h2>Notice.<br>Try.<br><em>Make it yours.</em></h2></div><div><article><span>01</span><div><h3>One useful idea</h3><p>Clear explanations with context and limitations. Explore the evidence without treating a product as a promise.</p></div></article><article><span>02</span><div><h3>A practice you can adapt</h3><p>Small exercises and flexible routines. General education, not a personal prescription or clinician-reviewed training.</p></div></article><article><span>03</span><div><h3>Space to reflect</h3><p>Bring your questions to a qualified healthcare professional when personal circumstances or treatment decisions are involved.</p></div></article></div></div></section>' + closing()
    body = body.replace(closing(), access_faq() + closing())
    page(data, api, "learning.html", "Matrix Academy", "Two original learning paths: everyday habits and independent network-marketing skills. Try an interactive free sample.", hero, body)

    hero = f'<section class="academy-hero academy-hero--partner"><div class="container">{masthead("learning.html", "Everyday learning")}<div class="academy-partner-intro"><div><p class="academy-label">02 / PARTNER PRACTICE</p><h1>Build skills.<br><em>Not pressure.</em></h1><p class="academy-partner-lead">A thoughtful introduction to independent business, the Zinzino products, and conversations people actually want to have.</p><a class="academy-button" href="#sample">Try the conversation exercise <span aria-hidden="true">↗</span></a><a class="academy-text-link" href="#curriculum">Explore the course map →</a><p class="academy-preview-note">Original course in development · Not available for purchase.</p></div><figure class="academy-partner-photo">{photo("partner-practice", "Illustrative scene of adults collaborating around a notebook and laptop.", hero=True)}<figcaption><span>Partner Practice</span><span>INDEPENDENT LEARNING</span></figcaption></figure></div></div></section>'
    body = '<section class="academy-section academy-section--brief"><div class="container academy-trust-strip"><h2>Clear expectations.<br>Room to decide.</h2><div><p>The Mindful Matrix is an independent partner, not Zinzino corporate. A commercial relationship may benefit us if you purchase or join through our partner connections. This is not an official Zinzino course.</p><p>Participation involves costs and uncertain results. The FTC cautions that many participants in legitimate multilevel marketing businesses earn little or nothing, and some lose money. Review current local agreements, costs, cancellation terms and official disclosures before deciding.</p><a href="https://consumer.ftc.gov/articles/multi-level-marketing-businesses-and-pyramid-schemes" target="_blank" rel="noopener noreferrer">Read the FTC consumer guide ↗<span class="visually-hidden"> (opens in a new tab)</span></a></div></div></section>'
    body += experience_summary(True) + sample_player(partner["practice"], True) + curriculum(partner, api, partner=True)
    products = {p["id"]: p for p in api.active_products(data["catalog"])}
    product_cards = []
    for pid in ("balance-test", "balanceoil-plus-300ml"):
        p = products[pid]
        product_cards.append(f'<a class="academy-product" href="products/{api.esc(pid, attribute=True)}.html"><img src="{api.esc(p["cutout"]["src"], attribute=True)}" alt="{api.esc(p["cutout"]["alt"], attribute=True)}" width="560" height="560" loading="lazy"><span>{api.esc(p["name"])} <b aria-hidden="true">↗</b></span></a>')
    body += f'<section class="academy-section"><div class="container academy-product-literacy"><div><p class="academy-label">PRODUCT LITERACY, NOT A SCRIPT</p><h2>Know what you are<br>talking about.</h2><p>Practise reading a label, explaining a test’s limits and distinguishing independent evidence from manufacturer information. Product familiarity is not medical expertise.</p><a class="academy-button academy-button--dark" href="testing.html">Explore the testing journeys ↗</a><p class="academy-small">Optional commercial products. We may earn a commission from purchases through our links. Buying products is not required to try the learning samples.</p></div><div class="academy-product-grid">{"".join(product_cards)}</div></div></section>'
    links = "".join(f'<li><a href="{api.esc(item["url"], attribute=True)}" target="_blank" rel="noopener noreferrer">{api.esc(item["title"])} ↗{api.external_note()}</a></li>' for item in partner["sources"])
    body += f'<section class="academy-section academy-section--white"><div class="container academy-faq"><div><p class="academy-label">BEFORE YOU DECIDE</p><h2>Good questions<br>belong here.</h2></div><div><details><summary>What should I expect from the course?</summary><p>No. This is an original education project, not an earnings promise. Understand the actual costs, responsibilities and uncertainty before considering participation.</p></details><details><summary>Is this official Zinzino training?</summary><p>No. The Mindful Matrix is independent. Proprietary back-office videos and training materials are not reproduced here. Links to official resources are not endorsements or permission to resell them.</p></details><details><summary>Can I join or buy the course now?</summary><p>No course enrollment or checkout is open. You can try the free sample and ask questions through our About page. Your visit does not enroll you or sign you up for marketing.</p></details><details><summary>Where does the guidance come from?</summary><p>Public official guidance, checked September 6, 2026. The Zinzino link is a commercial company source; other organizations do not endorse this course.</p><ul class="learning-source-links">{links}</ul></details></div></div></section>' + closing(True)
    body = body.replace('<p>No. This is an original education project, not an earnings promise.', '<p>This is original independent network-marketing education, not an earnings promise.')
    body = body.replace(closing(True), access_faq() + closing(True))
    page(data, api, "partners.html", "Partner Practice", "Independent network-marketing learning with product literacy, responsible marketing, networking, events and team skills. Try the free conversation exercise.", hero, body, "academy-page--partner")


def page(data, api, path, title, description, hero, body, track=""):
    head = api.document_head_markup(data["site"]["metadata"], prefix="", title=title + " | The Mindful Matrix", description=description, path=path,
        structured_data=[api.organization_schema(data["site"]["metadata"]), api.website_schema(data["site"]["metadata"]), api.breadcrumb_schema(data["site"]["metadata"], [("Home", ""), (title, path)])])
    head += f'\n<link rel="stylesheet" href="{api.versioned_asset("", "assets/css/academy.css")}">\n<script src="{api.versioned_asset("", "assets/js/academy.js")}" defer></script>'
    api.write_output(api.ROOT / path, api.render_template("academy.html", {
        "{{DOCUMENT_HEAD}}": head, "{{SHARED_HEADER}}": academy_header(api.shared_header_markup(data, prefix="", current=path.removesuffix(".html"))),
        "{{SHARED_FOOTER}}": api.shared_footer_markup(data, prefix=""), "{{TRACK_CLASS}}": api.esc(track, attribute=True),
        "{{ACADEMY_HERO}}": hero, "{{ACADEMY_BODY}}": body}))
